export function collectDom() {
  const $ = (id) => document.getElementById(id);
  const canvas = $("court");
  const ctx = canvas.getContext("2d", { alpha: false, desynchronized: true }) || canvas.getContext("2d");
  if (ctx) ctx.imageSmoothingEnabled = false;

  return {
    $,
    aiBtn: $("aiBtn"),
    browseRoomsBtn: $("browseRoomsBtn"),
    bottomControlInput: $("bottomControlInput"),
    canvas,
    copyRoomGameBtn: $("copyRoomGameBtn"),
    copyRoomBtn: $("copyRoomBtn"),
    controlCoach: $("controlCoach"),
    createPrivateBtn: $("createPrivateBtn"),
    ctx,
    dismissCoach: $("dismissCoach"),
    fillAiBtn: $("fillAiBtn"),
    flowBackBtn: $("flowBackBtn"),
    flowStatus: $("quickStatus"),
    flowTitle: $("flowTitle"),
    game: $("game"),
    hostPublicBtn: $("hostPublicBtn"),
    infoBtn: $("infoBtn"),
    infoModal: $("infoModal"),
    installBtn: $("installBtn"),
    joinPlayer: $("joinPlayer"),
    joinSpectator: $("joinSpectator"),
    leaderboard1v1: $("leaderboard1v1"),
    leaderboard2v2: $("leaderboard2v2"),
    leaveBtn: $("leaveBtn"),
    menu: $("menu"),
    modeStep: $("modeStep"),
    missesEl: $("misses"),
    networkBadge: $("networkBadge"),
    modeLabel: $("modeLabel"),
    nameInput: $("nameInput"),
    onlineBtn: $("onlineBtn"),
    onlineStep: $("onlineStep"),
    overlay: $("overlay"),
    playBtn: $("playBtn"),
    playFlow: $("playFlow"),
    playHome: $("playHome"),
    privateRoomBtn: $("privateRoomBtn"),
    privateStep: $("privateStep"),
    publicJoinPlayer: $("publicJoinPlayer"),
    publicJoinSpectator: $("publicJoinSpectator"),
    publicRoomCode: $("publicRoomCode"),
    quick1: $("quick1"),
    quick2: $("quick2"),
    quickBtn: $("quickBtn"),
    quickStatus: $("quickStatus"),
    renderDelayInput: $("renderDelayInput"),
    replayBtn: $("replayBtn"),
    resultScore: $("resultScore"),
    resultTitle: $("resultTitle"),
    roomCode: $("roomCode"),
    roomBadge: $("roomBadge"),
    roomLiveTab: $("roomLiveTab"),
    roomsRoot: $("rooms"),
    roomsStep: $("roomsStep"),
    roomValue: $("roomValue"),
    roomWaitingTab: $("roomWaitingTab"),
    settingsBtn: $("settingsBtn"),
    settingsModal: $("settingsModal"),
    settingsName: $("settingsName"),
    aiDifficulty: $("aiDifficulty"),
    soundInput: $("soundInput"),
    statusEl: $("status"),
    matchResult: $("matchResult"),
    timerEl: $("timer")
  };
}
