apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: monorally-gateway-pdb
  labels:
    app.kubernetes.io/name: monorally-gateway
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: monorally-gateway
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: monorally-worker-pdb
  labels:
    app.kubernetes.io/name: monorally-worker
spec:
  minAvailable: 75%
  selector:
    matchLabels:
      app.kubernetes.io/name: monorally-worker
