apiVersion: apps/v1
kind: Deployment
metadata:
  name: monorally-gateway
  labels:
    app.kubernetes.io/name: monorally-gateway
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: monorally-gateway
  template:
    metadata:
      labels:
        app.kubernetes.io/name: monorally-gateway
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8787"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: gateway
          image: ghcr.io/chinmaykrishnroy/monorally:1.12.2
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: "100m"
              memory: "64Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          ports:
            - name: http
              containerPort: 8787
          env:
            - name: PORT
              value: "8787"
            - name: SERVICE_ROLE
              value: "gateway"
            - name: BUS_TYPE
              value: "nats"
            - name: NATS_URL
              value: "nats://monorally-nats:4222"
            - name: DATA_BACKEND
              value: "postgres"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: monorally-secrets
                  key: database-url
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: monorally-secrets
                  key: redis-url
            - name: CORS_ORIGINS
              value: "https://mono.prefect-sys.online"
          readinessProbe:
            httpGet:
              path: /health/ready
              port: http
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health/live
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
