apiVersion: v1
kind: Service
metadata:
  name: monorally
  labels:
    app.kubernetes.io/name: monorally
spec:
  selector:
    app.kubernetes.io/name: monorally-gateway
  ports:
    - name: http
      port: 80
      targetPort: http
